spring:
  config:
    import: optional:file:.env[.properties]
  datasource:
    url: jdbc:mysql://localhost:3306/mock_project_db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Ho_Chi_Minh
    username: root
    password: 12345678
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect

  sql:
    init:
      mode: always


  mail:
    host: smtp.gmail.com
    port: 587
    username: anbui1435@gmail.com
    password: mryw jzak rhrg aiqb
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true

  servlet:
    multipart:
      max-file-size: 20GB
      max-request-size: 20GB

server:
  port: 8080

groq:
  api-key-1: ${GROQ_API_KEY_1}
  api-key-2: ${GROQ_API_KEY_2}
  api-key-3: ${GROQ_API_KEY_3}

vnpay:
  tmnCode: PYRHRA8O
  hashSecret: T2HWSMBX62REMQHPNCAPUVT8HTG3ISCX
  payUrl: https://sandbox.vnpayment.vn/paymentv2/vpcpay.html
  return-url: http://localhost:8080/api/vnpay/return
  ipn-url: http://localhost:8080/api/vnpay/ipn

tmdb:
  api-key: c696c9223931030b8bf2bca6ccce27e6
  base-url: https://api.themoviedb.org/3
  image-base-url: https://image.tmdb.org/t/p/w500

google:
  client-id: 849376005522-l2oe13172l2o9dklrqstm6i5mmcahukg.apps.googleusercontent.com

app:
  video:
    upload-dir: ${VIDEO_UPLOAD_DIR}
    work-dir: ${VIDEO_WORK_DIR}
    ffmpeg-path: ${FFMPEG_PATH}
    public-base-url: ${R2_PUBLIC_BASE_URL}
    hls-segment-seconds: 6

cloudflare:
  r2:
    account-id: ${CLOUDFLARE_R2_ACCOUNT_ID}
    access-key: ${CLOUDFLARE_R2_ACCESS_KEY}
    secret-key: ${CLOUDFLARE_R2_SECRET_KEY}
    bucket: ${CLOUDFLARE_R2_BUCKET}
    public-base-url: ${R2_PUBLIC_BASE_URL}

