-- Migration: drop unique constraints that enforced one comment per user/movie or per user/episode
-- IMPORTANT: backup your database before running this migration.
-- This script attempts to drop a set of likely index names created by different environments.
-- If your DB used different index names, run SHOW INDEX FROM reviews; and replace the index names below.

-- Attempt to drop indexes (IF EXISTS requires MySQL 8.0.13+). If your MySQL is older, run SHOW INDEX and DROP by exact name.
DROP INDEX IF EXISTS ux_reviews_user_movie ON reviews;
DROP INDEX IF EXISTS ux_reviews_user_episode ON reviews;
DROP INDEX IF EXISTS uk_reviews_user_movie ON reviews;
DROP INDEX IF EXISTS uk_reviews_user_episode ON reviews;
DROP INDEX IF EXISTS reviews_user_id_movie_id ON reviews;
DROP INDEX IF EXISTS reviews_user_id_episode_id ON reviews;
DROP INDEX IF EXISTS user_movie_unique ON reviews;
DROP INDEX IF EXISTS user_episode_unique ON reviews;

-- If your database created indexes with autogenerated names, you may need to inspect INFORMATION_SCHEMA:
-- SELECT INDEX_NAME FROM INFORMATION_SCHEMA.STATISTICS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'reviews' AND NON_UNIQUE = 0;

-- (Optional) Create non-unique indexes to keep lookups fast
CREATE INDEX IF NOT EXISTS idx_reviews_movie_id ON reviews(movie_id);
CREATE INDEX IF NOT EXISTS idx_reviews_episode_id ON reviews(episode_id);
CREATE INDEX IF NOT EXISTS idx_reviews_user_id ON reviews(user_id);
